services:
  # --- MEDIA SERVER ---
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    env_file:
      - ./provision/.env.defaults
    environment:
      - VERSION=docker
      - HOSTNAME="PlexServer"
    volumes:
      - ./provision/plex:/config
      - "${WIN_DATA_ROOT}/media/movies:/data/media/movies"
      - "${WIN_DATA_ROOT}/media/tv:/data/media/tv"
    ports:
      - "32400:32400/tcp" # Main Access
      - "1900:1900/udp" # DLNA
      - "32469:32469/tcp" # DLNA
      - "8324:8324/tcp" # Plex Companion
      - "32410:32410/udp" # GDM Discovery
      - "32412:32412/udp" # GDM Discovery
      - "32413:32413/udp" # GDM Discovery
      - "32414:32414/udp" # GDM Discovery
    privileged: true
    restart: unless-stopped
    networks:
      - media-network

  # --- REQUESTS & DISCOVERY ---
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    env_file:
      - ./provision/.env.defaults
    volumes:
      - ./provision/overseerr:/config
    ports:
      - "10500:5055"
    restart: unless-stopped
    networks:
      - media-network

  # --- MEDIA MANAGEMENT (ARRs) ---
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - ./provision/.env.defaults
    volumes:
      - ./provision/radarr:/config
      - "${WIN_DATA_ROOT}:/data"
    ports:
      - "10501:7878"
    restart: unless-stopped
    networks:
      - media-network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - ./provision/.env.defaults
    volumes:
      - ./provision/sonarr:/config
      - "${WIN_DATA_ROOT}:/data"
    ports:
      - "10502:8989"
    restart: unless-stopped
    networks:
      - media-network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file:
      - ./provision/.env.defaults
    volumes:
      - ./provision/prowlarr:/config
    ports:
      - "10503:9696"
    restart: unless-stopped
    networks:
      - media-network

  # --- DOWNLOADS ---
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file:
      - ./provision/.env.defaults
    environment:
      - WEBUI_PORT=10504
    volumes:
      - ./provision/qbittorrent:/config
      - "${WIN_DATA_ROOT}:/data"
    ports:
      - "10504:10504"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    networks:
      - media-network

  # --- DASHBOARD & UTILS ---
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    env_file:
      - ./provision/.env.defaults
    volumes:
      - ./provision/heimdall:/config
    ports:
      - "10505:80"
    restart: unless-stopped
    networks:
      - media-network

  #  watchtower:
  #    image: containrrr/watchtower:latest
  #    container_name: watchtower
  #    volumes:
  #      - /var/run/docker.sock:/var/run/docker.sock
  #    environment:
  #      - WATCHTOWER_CLEANUP=true
  #      - WATCHTOWER_POLL_INTERVAL=86400
  #    restart: unless-stopped
  #    networks:
  #      - media-network

  # --- SEARCH HELPERS ---
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "10506:8191"
    restart: unless-stopped
    networks:
      - media-network

networks:
  media-network:
    name: media-network
